name: Deploy
on:
  push:
    branches: [main]

jobs:
  infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/main
    permissions:
      id-token: write
      contents: read
    outputs:
      bucket-name: ${{ fromJSON(steps.output.outputs.stdout).bucket_name.value }}
    steps:
    - uses: actions/checkout@v6
    - uses: hashicorp/setup-terraform@v3
    - uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::268434236731:role/gha-adult-gymnastics-events
    - run: terraform init
    - run: terraform plan
    - run: terraform apply -auto-approve
    - id: output
      run: terraform output -json

  frontend:
    runs-on: ubuntu-latest
    needs: [infra]
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v5
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bun run build
    
    - uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::268434236731:role/gha-adult-gymnastics-events
    - run: |
        aws s3 sync \
          --delete \
          --exclude data/* \
          ./dist \
          s3://${{ needs.infra.outputs.bucket-name }}
