name: Deploy
on:
  push:
    branches: [main]

jobs:
  infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/main
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v6
    - uses: hashicorp/setup-terraform@v3
    - uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::268434236731:role/gha-adult-gymnastics-events
    - run: aws sts get-caller-identity
    - run: terraform init
    - run: terraform plan

  # buildfe:
  #   runs-on: ubuntu-latest
  #   needs: [infra]
  #   steps:
  #   - uses: actions/checkout@v5
  #   - uses: actions/setup-node@v
  #   - wor